overrides:
  glob: ^13.0.6
  katex: ^0.16.47
  vite: ^8.0.0-beta.16

allowedDeprecatedVersions:
  whatwg-encoding: '*'

allowBuilds:
  '@parcel/watcher': true
  cn-font-split: false
  esbuild: false
  koffi: false
  protobufjs: false
